tudong/tudong/Models/GAME.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tudong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAME
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GAME()
        {
            this.CHITIET_MUAGAME = new HashSet<CHITIET_MUAGAME>();
            this.CHITIET_MUAGAME1 = new HashSet<CHITIET_MUAGAME>();
        }
    
        public string idGame { get; set; }
        public string name { get; set; }
        public string moTa { get; set; }
        public int gia { get; set; }
        public Nullable<int> idNPH { get; set; }
        public string idTheLoai { get; set; }
        public string image_url { get; set; }
        public Nullable<System.DateTime> ngayTao { get; set; }
        public Nullable<int> giamGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_MUAGAME> CHITIET_MUAGAME { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_MUAGAME> CHITIET_MUAGAME1 { get; set; }
        public virtual USER USER { get; set; }
        public virtual THELOAI THELOAI { get; set; }
        public virtual THELOAI THELOAI1 { get; set; }
    }
}

tudong/tudong/Controllers/GAMEsController.cs
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;
using tudong.Models;

namespace tudong.Controllers
{
    public class GAMEsController : Controller
    {
        private QLCuaHangGameEntities4 db = new QLCuaHangGameEntities4();

        // GET: GAMEs
        public ActionResult IndexAdmin()
        {

            var gAMEs = db.GAMEs.Include(g => g.USER).Include(g => g.THELOAI);
           
            return View(gAMEs.ToList());
        }
        [HttpPost]
        public ActionResult IndexAdmin(string game)
        {
            var gAMEs = db.GAMEs.Include(g => g.USER).Include(g => g.THELOAI);

            if (!string.IsNullOrEmpty(game))
            {
                gAMEs = gAMEs.Where(s => s.name.Contains(game));
            }
            return View(gAMEs.ToList());
        }
        public ActionResult Index(string theLoai)
        {
           
            var gAMEs = db.GAMEs.Include(g => g.USER).Include(g => g.THELOAI);
            if (theLoai != "no")
                gAMEs = db.GAMEs.Where(abc => abc.idTheLoai == theLoai);
            return View(gAMEs.ToList());
        }

        [HttpPost]
        public ActionResult Index(string theLoai,String tenGame) {
            var gAMEs = db.GAMEs.SqlQuery("SELECT * FROM GAME WHERE name like '%"+@tenGame+"%'");
            return View(gAMEs.ToList());
        }
        public ActionResult AddCart(String idgame,int gia) {
            PLV.idgame.Add(idgame);
            PLV.tongTien += gia;
            return RedirectToAction("Cart");   
        }
        public ActionResult RemoveCart(String idgame,int gia)
        {
            PLV.idgame.Remove(idgame);
            PLV.tongTien -= gia;
            return RedirectToAction("Cart");
        }
        public ActionResult Cart()
        {
            var gAMEs = db.GAMEs.Include(g => g.USER).Include(g => g.THELOAI);
            ViewBag.sodu = db.USERS.FirstOrDefault(p => p.id.ToString() == PLV.Id).sodu;
            return View(gAMEs.ToList());
        }

        // GET: GAMEs/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GAME gAME = db.GAMEs.Find(id);
            if (gAME == null)
            {
                return HttpNotFound();
            }
            return View(gAME);
        }

        // GET: GAMEs/Create
        public ActionResult Create()
        {
            ViewBag.idNPH = new SelectList(db.USERS, "id", "FuName");
            ViewBag.idTheLoai = new SelectList(db.THELOAIs, "idTheLoai", "tenTheLoai");
            ViewBag.idg = db.GAMEs.Count() + 1;
            return View();
        }
        public ActionResult TrangTru() {
            return View();
        }
        // POST: GAMEs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idGame,name,moTa,gia,idNPH,idTheLoai,image_url,ngayTao,giamGia")] GAME gAME)
        {
            var imgG = Request.Files["Avatar"];
            //Lấy thông tin từ input type=file có tên Avatar
            string postedFileName = System.IO.Path.GetFileName(imgG.FileName);
            //Lưu hình đại diện về Server
            var path = Server.MapPath("/Images/" + postedFileName);
            imgG.SaveAs(path);
            if (ModelState.IsValid)
            {
                gAME.image_url = postedFileName;
                db.GAMEs.Add(gAME);
                db.SaveChanges();
                return RedirectToAction("Index",new {theLoai="no"});
               

            }

            ViewBag.idNPH = new SelectList(db.USERS, "id", "email", gAME.idNPH);
            ViewBag.idTheLoai = new SelectList(db.THELOAIs, "idTheLoai", "tenTheLoai", gAME.idTheLoai);
            return View(gAME);
        }
        public ActionResult DuaHoaDonCSDL()
        {
            MUAGAME n = new MUAGAME(PLV.MaMua, PLV.Id.AsInt(), false, "Đã thanh toán", DateTime.Now);
            db.MUAGAMEs.Add(n);
            db.SaveChanges();
            return RedirectToAction("DuaCTHoaDon");
        }
        public ActionResult DuaCTHoaDon()
        {
            for (int i = 1; i < PLV.idgame.Count(); i++) {
                int tt = db.CHITIET_MUAGAME.Count() + 1;
                string maGame = PLV.idgame[i].ToString();
                string maMua = PLV.MaMua;
               CHITIET_MUAGAME m = new CHITIET_MUAGAME();
                m.idChiTIet = tt;
                m.idGame = maGame;
                m.idMua= maMua;
                m.discount = 0;
                m.gia = db.GAMEs.FirstOrDefault(p => p.idGame == maGame).gia;
                db.CHITIET_MUAGAME.Add(m);
                db.SaveChanges();
            }
            int t1 = db.MUAGAMEs.Count() + 1;
            PLV.MaMua = "M" + t1;
            PLV.idgame.Clear();
            PLV.ListMuaGame.Clear();
            PLV.ListMaMuaBF.Clear();
            PLV.ListNgayMua.Clear();
            PLV.addgame("test");
            PLV.ListMaMuaBF.Add("test");
            PLV.ListNgayMua.Add("test");
            PLV.ListMuaGame.Add("test");
            db.USERS.FirstOrDefault(p => p.id.ToString() == PLV.Id).sodu-=PLV.tongTien;
            db.SaveChanges();
            PLV.tongTien = 0;
            foreach (var s in db.MUAGAMEs.ToList())
            {
                if (s.idND.ToString() == PLV.Id)
                    PLV.ListMuaGame.Add(s.idMua);
                PLV.ListNgayMua.Add(s.ngayMua.ToString());
            }

            foreach (var s in db.MUAGAMEs.ToList())
            {
                if (s.idND.ToString() == PLV.Id)
                    foreach (var r in db.CHITIET_MUAGAME.ToList())
                    {
                        if (r.idMua == s.idMua)
                            PLV.ListMaMuaBF.Add(r.idGame);

                    }
            }



            return View();
        }
        // GET: GAMEs/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GAME gAME = db.GAMEs.Find(id);
            if (gAME == null)
            {
                return HttpNotFound();
            }
            ViewBag.idNPH = new SelectList(db.USERS, "id", "email", gAME.idNPH);
            ViewBag.idTheLoai = new SelectList(db.THELOAIs, "idTheLoai", "tenTheLoai", gAME.idTheLoai);
            return View(gAME);
        }

        // POST: GAMEs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idGame,name,moTa,gia,idNPH,idTheLoai,image_url,ngayTao,giamGia")] GAME gAME)
        {
            if (ModelState.IsValid)
            {
                db.Entry(gAME).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idNPH = new SelectList(db.USERS, "id", "email", gAME.idNPH);
            ViewBag.idTheLoai = new SelectList(db.THELOAIs, "idTheLoai", "tenTheLoai", gAME.idTheLoai);
            return View(gAME);
        }

        // GET: GAMEs/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GAME gAME = db.GAMEs.Find(id);
            if (gAME == null)
            {
                return HttpNotFound();
            }
            return View(gAME);
        }

        // POST: GAMEs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            GAME gAME = db.GAMEs.Find(id);
            db.GAMEs.Remove(gAME);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult HomePage() {
            return View();
        }
        public ActionResult MyIndex()
        {

            var gAMEs = db.GAMEs.Include(g => g.USER).Include(g => g.THELOAI);
            
            return View(gAMEs.ToList());
        }
    }
}

tudong/tudong/Views/GAMEs/Cart.cshtml
@model IEnumerable<tudong.Models.GAME>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<script>
    function thongBaoTonTai() {
        alert("Trò chơi đã có trong giỏ hàng của bạn");

    }
    function thongBaoThemTC() {
        alert("Bạn đã thêm vào giỏ hàng!");

    }
</script>
<style>
    .container{
        min-height:600px;
    }
</style>
<div class="container">

    <h1 style=" margin-top:30px;font-family:'Bell MT';center;color:darkslategray;font-weight:bold;font-size:50px; text-align:center">GIỎ HÀNG CỦA BẠN</h1>
    <style>
        .button {
            display: inline-block;
            padding: 10px 20px;
            font-size: 16px;
            text-align: center;
            text-decoration: none;
            background-color: #4CAF50;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        .box {
            border: 1px solid #ccc;
            padding: 10px;
            margin-bottom: 40px;
            display: block;
            align-items: center;
        }
    </style>

    @if (tudong.Models.PLV.idgame.Count == 1)
    {
        <h2 style="text-align:center;color:red; margin-left:20px">Chưa có game nào được thêm vào</h2>
    }
    @foreach (var item in Model)
    {
        if (tudong.Models.PLV.idgame.Contains(item.idGame))
        {

            <div class="box" style="display: flex; align-items: center; background-color: #333; padding: 10px; border-radius: 5px; witdh: 20%">
                <div style="flex-grow: 0; width: 10%;">
                    <img src="~/Images/@item.image_url" alt="Ảnh" style="width: 100%; aspect-ratio: 1/1; object-fit: cover; border-radius: 5px;">
                </div>
                <div style="flex-grow: 1;">
                    <div style="margin-left: 10px; font-size: 18px; font-weight: bold; color: #fff; text-shadow: 1px 1px 2px #000;">@Html.DisplayFor(modelItem => item.name)</div>
                    <div style="margin-left: 10px; color: #fff; font-weight: bold;">@Html.DisplayFor(modelItem => item.gia)</div>
                </div>
                <button onlcick="thongBaDaThem()">
                    <p>@Html.ActionLink("Xóa khỏi giỏ hàng", "RemoveCart", "GAMEs", new { idgame = item.idGame, gia = item.gia }, new { @class = "a" });</p>

                </button>
            </div>
        }
    }
    <h2 style="margin-left:20px">Số dư : @ViewBag.soDu đồng</h2>
    <h2 style="margin-left:20px">Tông tiền là : @tudong.Models.PLV.tongTien đồng</h2>
    @if (ViewBag.sodu > tudong.Models.PLV.tongTien)
    {
        if (tudong.Models.PLV.idgame.Count() > 1)
        {
            <p>@Html.ActionLink("Thanh toán", "DuaHoaDonCSDL", "GAMEs", new { @class = "button" });</p>
        }
    }
    else
    {
        <h1>Không đủ tiền</h1>
    }

    </table>

</div>

tudong/tudong/Views/GAMEs/Create.cshtml
@model tudong.Models.GAME

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<style>
    .custom-form {
        margin: 20px;
        padding: 20px;
        background-color: #f0f0f0;
        border-radius: 5px;
    }

        .custom-form .form-heading {
            font-size: 18px;
            font-weight: bold;
            margin-bottom: 10px;
        }

        .custom-form .form-divider {
            border: none;
            border-top: 1px solid #ccc;
            margin: 10px 0;
        }

        .custom-form .form-group {
            margin-bottom: 15px;
        }

        .custom-form .control-label {
            font-weight: bold;
        }

        .custom-form .btn {
            background-color: #007bff;
            color: #fff;
            border-color: #007bff;
        }

            .custom-form .btn:hover {
                background-color: #0056b3;
                border-color: #0056b3;
            }

</style>

<h2>Thêm một phần mềm mới</h2>

@using (Html.BeginForm("Create", "GAMEs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal custom-form">
    <h4 class="form-heading">GAME</h4>
    <hr class="form-divider" />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.idGame, new { Value = ViewBag.idg })
    @Html.HiddenFor(model => model.ngayTao, new { Value = @DateTime.UtcNow.ToString("dd/MM/yyyy") })

   

    <div class="form-group">
        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.moTa, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.moTa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.moTa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.gia, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.gia, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.gia, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.HiddenFor(model => model.idNPH, new { Value = tudong.Models.PLV.Id.AsInt() })

    <div class="form-group">
        @Html.LabelFor(model => model.idTheLoai, "idTheLoai", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("idTheLoai", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.idTheLoai, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            <div class="avatar-wrapper">
                <img id="avatar-preview" src="~/Images/avatar.jpg" alt="Avatar Preview" /> <br />
                <input type="file" style="height:30px;" name="Avatar" accept="image/*" required />
                @Html.ValidationMessageFor(model => model.image_url, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    

    <div class="form-group">
        @Html.LabelFor(model => model.giamGia, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.giamGia, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.giamGia, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

tudong/tudong/Views/GAMEs/Details.cshtml
@model tudong.Models.GAME

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<head>
    <style>
        .container {
            
        
        }
    </style>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <title>Lugx Gaming - Product Detail</title>

    <!-- Bootstrap core CSS -->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="~/assets/css/fontawesome.css">
    <link rel="stylesheet" href="~/assets/css/templatemo-lugx-gaming.css">
    <link rel="stylesheet" href="~/assets/css/owl.css">
    <link rel="stylesheet" href="~/assets/css/animate.css">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css" />
    <!--

    TemplateMo 589 lugx gaming

    https://templatemo.com/tm-589-lugx-gaming

    -->
</head>
<style>
    
</style>

<div class="page-heading header-text">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h3>@Html.DisplayFor(model => model.name)</h3>
            </div>
        </div>
    </div>
</div>

<div class="single-product section">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="left-image">
                    <img src="~/Images/@Html.DisplayFor(model => model.image_url)" alt="">
                </div>
            </div>
            <div class="col-lg-6 align-self-center">
                <h4>
                    @Html.DisplayFor(model => model.name)
                </h4>
                <span class="price">
                    @Html.DisplayFor(model => model.gia) vnd
                </span>
                <p>
                    @Html.DisplayFor(model => model.moTa)
                </p>
                <form id="qty" action="#">
                    
                    <button type="submit"><i class="fa fa-shopping-bag"></i>
                    @Html.ActionLink("Mua", "AddCart", "GAMEs", new { idgame = @Html.DisplayFor(model => model.idGame), gia = @Html.DisplayFor(model => model.gia) }, new { @class = "a" })
</button>
                </form>
                <ul>
                    <li><span>Game ID:</span> @Html.DisplayFor(model => model.idGame)</li>
                    <li><span>Genre:</span> <a href="#">@Html.DisplayFor(model => model.THELOAI.tenTheLoai)</a>
                    <li><span>Publish:</span> <a href="#">@Html.DisplayFor(model => model.ngayTao)</a>

                    <li><span>Developer:</span> <a href="#">@Html.DisplayFor(model => model.USER.FuName)</a>

                </ul>
            </div>
            <div class="col-lg-12">
                <div class="sep"></div>
            </div>
        </div>
    </div>
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.idGame }) |
    @Html.ActionLink("Back to List", "Index")
</p>
<script src="~/vendor/jquery/jquery.min.js"></script>
<script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>
<script src="~/assets/js/isotope.min.js"></script>
<script src="~/assets/js/owl-carousel.js"></script>
<script src="~/assets/js/counter.js"></script>
<script src="~/assets/js/custom.js"></script>

tudong/tudong/Views/GAMEs/DuaCTHoaDon.cshtml
@{
    ViewBag.Title = "DuaCTHoaDon";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<h1 style="margin-top:50px;margin-bottom:50px;text-align:center">CẢM ƠN BẠN ĐÃ MUA HÀNG, CHÚC BẠN MỘT NGÀY TỐT LÀNH</h1>
<h2 style="text-align:center">@Html.ActionLink("Tiếp tục khám phá", "Index", "GAMEs", new { theLoai = "no" }, new { @class = "a" })&nbsp; &nbsp;</h2>

tudong/tudong/Views/GAMEs/DuaHoaDonCSDL.cshtml
@{
    ViewBag.Title = "DuaHoaDonCSDL";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>CẢM ƠN BẠN ĐÃ MUA HÀNG, CHÚC BẠN MỘT NGÀY TỐT LÀNH</h2>

tudong/tudong/Views/GAMEs/TrangTru.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="banner_section layout_padding">
    <div class="container">
        <div id="my_slider" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <div class="row">
                        <div class="col-md-6">
                            <h1 class="video_text">NEWS</h1>
                            <h1 class="controller_text">RESIDENT EVIL 4</h1>
                            <p class="banner_text">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable</p>

                            <div class="shop_bt"><a href="@Url.Action("Details", new { id = "G005" })">Chi tiết</a></div>
                        </div>
                        <div class="col-md-6">
                            <div class="image_1">
                                <img src="~/images/residentevil.jpg" width="800" height="500">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="row">
                        <div class="col-md-6">
                            <h1 class="video_text">UPDATE</h1>
                            <h1 class="controller_text">MINECRAFT 1.7.8</h1>
                            <p class="banner_text">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable</p>
                            <div class="shop_bt"><a href="@Url.Action("Details", new { id = "G001" })">CHI TIẾT</a></div>
                        </div>
                        <div class="col-md-6">
                            <div class="image_1"><img src="~/images/anhtemp.jpg" width="400" height="200"></div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="row">
                        <div class="col-md-6">
                            <h1 class="video_text">TOP</h1>
                            <h1 class="controller_text">GAME OF THE YEAR</h1>
                            <p class="banner_text">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable</p>
                            <div class="shop_bt"><a href="#">@Html.ActionLink("SHOP NOW", "Index", "GAMEs", new { theLoai = "no" }, new { @class = "" })</a></div>
                        </div>
                        <div class="col-md-6">
                            <div class="image_1"><img src="~/images/homepage.jpg"></div>
                        </div>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#my_slider" role="button" data-slide="prev">
                <i class="fa fa-angle-left"></i>
            </a>
            <a class="carousel-control-next" href="#my_slider" role="button" data-slide="next">
                <i class="fa fa-angle-right"></i>
            </a>
        </div>
    </div>
</div>
<div class="about_section layout_padding">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="image_2"><img src="~/images/gta.jpg" height="400px"></div>
            </div>
            <div style="margin-top:300px" class="col-md-6">
                <h1 class="about_text">TRIOLYGY</h1>
                <p class="lorem_text">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable</p>
                <div class="shop_bt_2"><a href="">@Html.ActionLink("GAME", "Index", "GAMEs", new { theLoai = "no" }, new { @class = "" })</a></div>
            </div>
        </div>
    </div>
</div>
<div class="video_section layout_padding">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h1 class="video_text_2">3d video game</h1>
                <h1 class="controller_text_2">remoto control</h1>
                <p class="banner_text_2">Sự thịnh hành của VR và 3D GAME ở thời điểm hiện tại cũng như tương lai tới, metavers</p>
               
            </div>
            <div class="col-md-6">
                <div class="image_4"><img src="~/images/img-4.png"></div>
            </div>
        </div>
    </div>
</div>