tudong/tudong/Models/MUAGAME.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tudong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUAGAME
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MUAGAME()
        {
            this.CHITIET_MUAGAME = new HashSet<CHITIET_MUAGAME>();
            this.CHITIET_MUAGAME1 = new HashSet<CHITIET_MUAGAME>();
        }
    
        public string idMua { get; set; }
        public Nullable<int> idND { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string trangThai { get; set; }
        public Nullable<System.DateTime> ngayMua { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_MUAGAME> CHITIET_MUAGAME { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_MUAGAME> CHITIET_MUAGAME1 { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
        public MUAGAME(string idMua, int? idND, bool? Deleted, string trangThai, DateTime? ngayMua) : this()
        {
            this.idMua = idMua;
            this.idND = idND;
            this.Deleted = Deleted;
            this.trangThai = trangThai;
            this.ngayMua = ngayMua;
        }
    }
}

tudong/tudong/Controllers/MUAGAMEsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using tudong.Models;

namespace tudong.Controllers
{
    public class MUAGAMEsController : Controller
    {
        private QLCuaHangGameEntities4 db = new QLCuaHangGameEntities4();

        // GET: MUAGAMEs
        public ActionResult Index()
        {
            var mUAGAMEs = db.MUAGAMEs.Include(m => m.USER);
            return View(mUAGAMEs.ToList());
        }
        [HttpPost]
        public ActionResult Index(string maHD)
        {
            var mUAGAMEs = db.MUAGAMEs.Include(m => m.USER);

            if (!string.IsNullOrEmpty(maHD))
            {
                mUAGAMEs = mUAGAMEs.Where(s => s.idMua.Contains(maHD));
            }
            return View(mUAGAMEs.ToList());
        }
        public ActionResult Cart()
        {
            
            return View();
        }
        // GET: MUAGAMEs/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MUAGAME mUAGAME = db.MUAGAMEs.Find(id);
            if (mUAGAME == null)
            {
                return HttpNotFound();
            }
            return View(mUAGAME);
        }

        // GET: MUAGAMEs/Create
        public ActionResult Create(string idtk)
        {
            PLV.MaMua = "M" + db.MUAGAMEs.Count();
            ViewBag.idND = new SelectList(db.USERS, "id", "email");
            return View();
        }

        // POST: MUAGAMEs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idMua,idND,Deleted,trangThai,ngayMua")] MUAGAME mUAGAME)
        {
            if (ModelState.IsValid)
            {
                db.MUAGAMEs.Add(mUAGAME);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idND = new SelectList(db.USERS, "id", "email", mUAGAME.idND);
            return View(mUAGAME);
        }

        // GET: MUAGAMEs/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MUAGAME mUAGAME = db.MUAGAMEs.Find(id);
            if (mUAGAME == null)
            {
                return HttpNotFound();
            }
            ViewBag.idND = new SelectList(db.USERS, "id", "email", mUAGAME.idND);
            return View(mUAGAME);
        }

        // POST: MUAGAMEs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idMua,idND,Deleted,trangThai,ngayMua")] MUAGAME mUAGAME)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mUAGAME).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idND = new SelectList(db.USERS, "id", "email", mUAGAME.idND);
            return View(mUAGAME);
        }

        // GET: MUAGAMEs/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MUAGAME mUAGAME = db.MUAGAMEs.Find(id);
            if (mUAGAME == null)
            {
                return HttpNotFound();
            }
            return View(mUAGAME);
        }

        // POST: MUAGAMEs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            MUAGAME mUAGAME = db.MUAGAMEs.Find(id);
            
            db.MUAGAMEs.Remove(mUAGAME);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult GioHang(string id)
        {
            if (id != null)
            {
                ViewBag.idnd = id;
                ViewBag.role = db.USERS.FirstOrDefault(p => p.id.ToString() == id).idRole.ToString();
                ViewBag.name = db.USERS.FirstOrDefault(p => p.id.ToString() == id).FuName;
            }
            else
            {
                ViewBag.role = "0";
                ViewBag.idnd = "ERROR";
                ViewBag.name = "ERROR";
            }

            ViewBag.idmua = "M" + db.MUAGAMEs.Count();
            
            ViewBag.idND = new SelectList(db.USERS, "id", "email");

            return View();
        }
        
        
        // POST: MUAGAMEs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GioHang([Bind(Include = "idMua,idND,Deleted,trangThai,ngayMua")] MUAGAME mUAGAME)
        {
            if (ModelState.IsValid)
            {
                db.MUAGAMEs.Add(mUAGAME);
                db.SaveChanges();
                return RedirectToAction("Index","GAMEs");
            }
            ViewBag.idND = new SelectList(db.USERS, "id", "email", mUAGAME.idND);
            return View(mUAGAME);
        }
    }
}

tudong/tudong/Views/MUAGAMEs/Create.cshtml
@model tudong.Models.MUAGAME


@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Giỏ hàng của bạn</h2>

@using (Html.BeginForm("Create", "MUAGAMEs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
<p>
    role @ViewBag.role ;
    name @ViewBag.name ;
    nd @ViewBag.idtk;
    id @ViewBag.idmua;
</p>
<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @Html.HiddenFor(model => model.idMua, new { Value = ViewBag.idmua })
    @Html.HiddenFor(model => model.idND, new { Value = ViewBag.idtk })
    @Html.HiddenFor(model => model.trangThai, new { Value = "0" })
    @Html.HiddenFor(model => model.ngayMua, new { Value = DateTime.Now })


    
    @Html.Action("Index", "CHITIET_MUAGAME")


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Thanh toán" class="btn btn-default" />
        </div>
    </div>

</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

tudong/tudong/Views/MUAGAMEs/Delete.cshtml
@model tudong.Models.MUAGAME

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MUAGAME</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Deleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Deleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.trangThai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.trangThai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ngayMua)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ngayMua)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.USER.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.USER.email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

tudong/tudong/Views/MUAGAMEs/Details.cshtml
@model tudong.Models.MUAGAME

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>MUAGAME</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.idMua)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.idMua)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.idND)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.idND)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Deleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Deleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.trangThai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.trangThai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ngayMua)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ngayMua)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.USER.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.USER.email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.idMua }) |
    @Html.ActionLink("Back to List", "Index")
</p>

tudong/tudong/Views/MUAGAMEs/Edit.cshtml
@model tudong.Models.MUAGAME

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MUAGAME</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idMua)

        <div class="form-group">
            @Html.LabelFor(model => model.idND, "idND", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idND", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idND, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Deleted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Deleted)
                    @Html.ValidationMessageFor(model => model.Deleted, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.trangThai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.trangThai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.trangThai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ngayMua, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ngayMua, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ngayMua, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

tudong/tudong/Views/MUAGAMEs/GioHang.cshtml
@model tudong.Models.MUAGAME

@{
    ViewBag.Title = "GioHang";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>GioHang</h2>
<p1>
    idgame 1 @tudong.Models.PLV.ListMaMuaBF[0];
    idgame 1 @tudong.Models.PLV.ListMaMuaBF[1];
</p1>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    if (ViewBag.role != "0")
    {

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            @Html.HiddenFor(model => model.idMua, new { Value = ViewBag.idnd })
            @Html.HiddenFor(model => model.idND, new { Value = ViewBag.idmoi })
            @Html.HiddenFor(model => model.trangThai, new { Value = "0" })
            @Html.HiddenFor(model => model.ngayMua, new { Value = DateTime.Now })

            <form id="paymentForm" method="post" action="Payment">
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Thêm trò chơi vào giỏ" class="btn btn-default" />
                    </div>
                </div>
            </form>
        </div>
    }
    else
    {
        <h2>Bạn phải đăng nhập để sử dụng giỏ hàng</h2>

    }
}

tudong/tudong/Views/MUAGAMEs/Index.cshtml
@model IEnumerable<tudong.Models.MUAGAME>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "TenSV", rowsPerPage: 5);
}
<style>
    .container {
        display: flex;
        justify-content: center;
        align-items: center;
        margin-top: 10px;
        margin-bottom:10px;
    }

        .container input[type="text"] {
            width: 700px;
            height: 40px;
            padding: 5px;
            font-size: 16px;
        }

        .container input[type="submit"] {
            width: 150px;
            height: 40px;
            font-size: 16px;
            background-color: darkslategrey;
            color: white;
            border: none;
            cursor: pointer;
        }
</style>
<h2>Index</h2>
@using (Html.BeginForm())
{
    <div class="container">
        <input type="text" name="maHD" placeholder="nhập mã hoá đơn" />
        <input type="submit" value="Tìm kiếm" />
    </div>
}
<div id="gridContent" style="text-align:center">
    @ViewBag.TB
    @grid.GetHtml(
        tableStyle: "table table-bordered table-hover grid-table",
        footerStyle: "grid-footer",
        fillEmptyRows: true,
        mode: WebGridPagerModes.Numeric,
        alternatingRowStyle: "alternatingRowStyle",
          columns: new[]  // colums in grid
         {
    grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
    grid.Column("idMua","Id Hoá Đơn"), //the model fields to display
    grid.Column("idND","Id người dùng"  ),
    grid.Column("Deleted","Trạng thái",format: (@item) => @item.Deleted==true?"Duyệt":"Chưa duyệt"),
    grid.Column("trangThai","Mật khẩu"),
grid.Column("ngayMua","Email"),
grid.Column("USER.email","FuName"),
grid.Column("Chức năng", format: @<text>
    <a href="@Url.Action("Edit",
                        new { id = item.idMua})" class="edit-btn"><abbr title="Cập nhật dữ liệu"><img src="/images/edit.png" width="20" height="20" /></abbr></a>
    <a href="@Url.Action("Details",
                        new { id = item.idMua})" class="edit-btn"><abbr title="Xem chi tiết"><img src="/images/details.png" width="20" height="20" /></abbr></a>
    <a href="@Url.Action("Delete",
                        new { id = item.idMua})" class="edit-btn">
        <abbr title="Xóa dữ liệu">
            <img src="/images/delete.png" width="20" height="20" />
        </abbr>
    </a>
</text>),
}
)
</div>