tudong/tudong/Models/USER.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tudong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.GAMEs = new HashSet<GAME>();
            this.MUAGAMEs = new HashSet<MUAGAME>();
            this.MUAGAMEs1 = new HashSet<MUAGAME>();
        }
    
        public int id { get; set; }
        public string email { get; set; }
        public string tentaikhoan { get; set; }
        public string matKhau { get; set; }
        public string sdt { get; set; }
        public Nullable<int> idRole { get; set; }
        public Nullable<System.DateTime> ngaySinh { get; set; }
        public string FuName { get; set; }
        public string Avartar { get; set; }
        public Nullable<int> sodu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GAME> GAMEs { get; set; }
        public virtual IDROLE IDROLE1 { get; set; }
        public virtual IDROLE IDROLE2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MUAGAME> MUAGAMEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MUAGAME> MUAGAMEs1 { get; set; }
    }
}

tudong/tudong/Controllers/USERsController.cs
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using tudong.Models;
using WebGrease.Css.Extensions;

namespace tudong.Controllers
{
    public class USERsController : Controller
    {
        private readonly DbContext _dbContext; // Thay thế DbContext bằng lớp DbContext thực tế của bạn
        private QLCuaHangGameEntities4 db = new QLCuaHangGameEntities4();

        // GET: USERs
        public ActionResult Index()
        {
            
            var uSERS = db.USERS.Include(u => u.IDROLE1);

            return View(uSERS.ToList());
        }
        [HttpPost]
        public ActionResult Index(string maND)
        {
            var uSERS = db.USERS.Include(u => u.IDROLE1);

            if (!string.IsNullOrEmpty(maND))
            {
                uSERS = uSERS.Where(s => s.id.ToString().Contains(maND)||s.tentaikhoan.Contains(maND));
            }
            return View(uSERS.ToList());
        }

        // GET: USERs/Details/5
        public ActionResult Details(int? idtk)
        {
            if (idtk == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            USER uSER = db.USERS.Find(idtk);
            if (uSER == null)
            {
                return HttpNotFound();
            }
            return View(uSER);
        }

        // GET: USERs/Create
        public ActionResult Create()
        {
            ViewBag.idRole = new SelectList(db.IDROLEs, "idRole1", "ten");
            int i = db.USERS.Count() + 10;
            ViewBag.iddk = ""+i;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        // POST: USERs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        public ActionResult Create([Bind(Include = "id,email,tentaikhoan,matKhau,sdt,idRole,ngaySinh,FuName,Avartar,sodu")] USER uSER)
        {
            //System.Web.HttpPostedFileBase Avatar;
            var imgNV = Request.Files["Avatar"];
            //Lấy thông tin từ input type=file có tên Avatar
            string postedFileName = System.IO.Path.GetFileName(imgNV.FileName);
            //Lưu hình đại diện về Server
            var path = Server.MapPath("/Images/" + postedFileName);
            imgNV.SaveAs(path);
            if (ModelState.IsValid)
            {
                uSER.Avartar = postedFileName;
                db.USERS.Add(uSER);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idRole = new SelectList(db.IDROLEs, "idRole1", "ten", uSER.idRole);
            return View(uSER);
        }

        // GET: USERs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            USER uSER = db.USERS.Find(id);
            if (uSER == null)
            {
                return HttpNotFound();
            }
            ViewBag.idRole = new SelectList(db.IDROLEs, "idRole1", "ten", uSER.idRole);
            return View(uSER);
        }

        // POST: USERs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,email,tentaikhoan,matKhau,sdt,idRole,ngaySinh,FuName,Avartar,sodu")] USER uSER)
        {
            if (ModelState.IsValid)
            {
                db.Entry(uSER).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idRole = new SelectList(db.IDROLEs, "idRole1", "ten", uSER.idRole);
            return View(uSER);
        }

        // GET: USERs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            USER uSER = db.USERS.Find(id);
            if (uSER == null)
            {
                return HttpNotFound();
            }
            return View(uSER);
        }

        // POST: USERs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            USER uSER = db.USERS.Find(id);
            db.USERS.Remove(uSER);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Login() {
            PLV.role = null;
            PLV.addgame("test");
            PLV.MaMua = null;
            PLV.Name = null;
            return View();
        }
        [HttpPost]
        public ActionResult Login(LoginVM model)
        {
            
            if (ModelState.IsValid)
            {
               
                // Kiểm tra thông tin đăng nhập trong CSDL
                bool isValid = CheckLoginCredentials(model.Username, model.Password);

                if (isValid)
                {

                    // Đăng nhập thành công, thực hiện các tác vụ khác (ví dụ: lưu thông tin đăng nhập vào session)
                    // Chuyển hướng đến trang chính hoặc trang nào đó
                    PLV.Id = checkID(model.Username, model.Password);
                    PLV.role = db.USERS.FirstOrDefault(p => p.id.ToString() == PLV.Id).idRole.ToString();
                    PLV.Name = db.USERS.FirstOrDefault(p => p.id.ToString() == PLV.Id).FuName;
                   
                    int tt = db.MUAGAMEs.Count() + 1;
                    PLV.MaMua = "M" + tt;
                    PLV.idgame.Clear();
                    PLV.ListMuaGame.Clear();
                    PLV.ListMaMuaBF.Clear();
                    PLV.ListNgayMua.Clear();
                    PLV.addgame("test");       
                    PLV.ListMaMuaBF.Add("test");
                    PLV.ListNgayMua.Add("test");
                    PLV.ListMuaGame.Add("test");
                    PLV.tongTien = 0;
                    foreach (var s in db.MUAGAMEs.ToList())
                    {
                        if(s.idND.ToString()==PLV.Id)
                            PLV.ListMuaGame.Add(s.idMua);
                        PLV.ListNgayMua.Add(s.ngayMua.ToString());
                    }
                    
                    foreach (var s in db.MUAGAMEs.ToList()) {
                        if(s.idND.ToString()==PLV.Id)
                            foreach(var r in db.CHITIET_MUAGAME.ToList())
                            {
                                if (r.idMua == s.idMua)
                                    PLV.ListMaMuaBF.Add(r.idGame);
                            }
                    }
                    return RedirectToAction("TrangTru", "GAMEs");
                }
                else
                {
                    ModelState.AddModelError("", "Tên đăng nhập hoặc mật khẩu không hợp lệ.");
                }
            }

            // Nếu thông tin đăng nhập không hợp lệ, hiển thị lại trang đăng nhập với thông báo lỗi
            return View(model);
        }

        private bool CheckLoginCredentials(string username, string password)
        {
            // Thực hiện kiểm tra thông tin đăng nhập trong CSDL sử dụng Entity Framework
            if (db.USERS.Any(p => p.tentaikhoan == username && p.matKhau == password))
                return true;
            return false;
        }
        private string checkID(string username, string password)
        {
            if (db.USERS.Any(p => p.tentaikhoan == username && p.matKhau == password))
            {
                var user = db.USERS.FirstOrDefault(p => p.tentaikhoan == username && p.matKhau == password);
                if (user != null)
                {
                    return user.id.ToString();
                }
            }
            return null;
        }


        public ActionResult test() {
            return View();
                }

    }
}

tudong/tudong/Views/USERs/Create.cshtml
@model tudong.Models.USER

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Đăng ký</h2>
<link rel="stylesheet" href="@Url.Content("~/Content/registeruser.css")" />
@using (Html.BeginForm("Create", "USERs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="form-container">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    <div class="col-md-10">
                        <div class="avatar-wrapper">
                            <img id="avatar-preview" src="~/Images/avatar.jpg" alt="Avatar Preview" /> <br />
                            <input type="file" style="height:30px;" name="Avatar" accept="image/*" required />
                            @Html.ValidationMessageFor(model => model.Avartar, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                @Html.HiddenFor(model => model.id, new { Value = ViewBag.iddk })


                <div class="form-group">
                    @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.tentaikhoan, "Username", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.tentaikhoan, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.tentaikhoan, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.matKhau, "Password", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.matKhau,  new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.matKhau, "", new { @class = "text-danger" })
                    </div>
                </div>
            <div class="form-group">
                @Html.LabelFor(model => model.sdt, "Phone", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.sdt,  new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.sdt, "", new { @class = "text-danger" })
                </div>
            </div>

            @Html.HiddenFor(model => model.idRole, new { Value = 3 })


            <div class="form-group">
                @Html.LabelFor(model => model.ngaySinh,"Birthday", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ngaySinh, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ngaySinh, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FuName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FuName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FuName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.idRole,"Role", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("idRole", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.idRole, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.sodu,"Budget", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.sodu, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.sodu, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>

        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

tudong/tudong/Views/USERs/Delete.cshtml
@model tudong.Models.USER

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>USER</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tentaikhoan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tentaikhoan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.matKhau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.matKhau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sdt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sdt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ngaySinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ngaySinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FuName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FuName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Avartar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Avartar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sodu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sodu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IDROLE1.ten)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IDROLE1.ten)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

tudong/tudong/Views/USERs/Details.cshtml
@model tudong.Models.USER

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Profile</title>
    <style>
        body {
        }

        .container {
            margin-top:50px;
           min-height:500px;
        }

        .profile-image {
            width: 150px;
            height: 150px;
            border-radius: 50%;
            overflow: hidden;
            margin-right: 20px;
        }

            .profile-image img {
                width: 100%;
                height: 100%;
                object-fit: cover;
            }

        .profile-info {
            flex-grow: 1;
        }

        .profile-name {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 10px;
        }

        .profile-email {
            color: #666;
            margin-bottom: 10px;
        }

        .profile-bio {
            color: #333;
            margin-bottom: 20px;
        }

        .profile-details {
            display: flex;
            flex-wrap: wrap;
        }

            .profile-details div {
                flex-basis: 50%;
                padding: 5px 0;
            }

        .profile-label {
            font-weight: bold;
        }

        .profile-value {
            color: #333;
        }

        .profile-skills {
            margin-top: 20px;
        }

        .profile-skill {
            display: inline-block;
            background-color: #f2f2f2;
            color: #333;
            padding: 5px 10px;
            margin-right: 10px;
            margin-bottom: 10px;
            border-radius: 4px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="profile-image">
            <img src="~/Images/@Html.DisplayFor(model => model.Avartar)" alt="ER'''Imgae not found'''R">
        </div>
        <div class="profile-info">
            <div class="profile-name">@Html.DisplayFor(model => model.tentaikhoan)</div>
            <div class="profile-email">@Html.DisplayFor(model => model.email)</div>
            <div class="profile-details">
                <div>
                    <span class="profile-label">SDT:</span>
                    <span class="profile-value">@Html.DisplayFor(model => model.sdt)</span>
                </div>
                <div>
                    <span class="profile-label">Ngày sinh:</span>
                    <span class="profile-value">@Html.DisplayFor(model => model.ngaySinh)</span>
                </div>
                <div>
                    <span class="profile-label">Quyền:</span>
                    <span class="profile-value">@Html.DisplayFor(model => model.IDROLE1.ten)</span>
                </div>
                <div>
                    <span class="profile-label">Số dư:</span>
                    <span class="profile-value">@Html.DisplayFor(model => model.sodu)</span>
                </div>
                @if (tudong.Models.PLV.role == "1")
                {

                    <div>
                        <span class="profile-label">TRUY CẬP:</span>
                        <div class="profile-lable">Tai Khoan:</div>
                        <div class="profile-value"> @Html.DisplayFor(model => model.tentaikhoan)</div>
                        <div class="profile-lable">MatKhau:</div>
                        <div class="profile-value">@Html.DisplayFor(model => model.matKhau)</div>
                    </div>
                }
            </div>


        </div>
    </div>
</body>

tudong/tudong/Views/USERs/Edit.cshtml
@model tudong.Models.USER

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>USER</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tentaikhoan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tentaikhoan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tentaikhoan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.matKhau, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.matKhau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.matKhau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sdt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sdt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sdt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idRole, "idRole", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idRole", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idRole, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ngaySinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ngaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ngaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FuName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FuName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FuName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Avartar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Avartar, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Avartar, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sodu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sodu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sodu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

tudong/tudong/Views/USERs/Index.cshtml
@model IEnumerable<tudong.Models.USER>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "TenSV", rowsPerPage: 5);
}
<style>
    .container {
        display: flex;
        justify-content: center;
        align-items: center;
        margin-top: 10px;
        margin-bottom:10px;
    }

        .container input[type="text"] {
            width: 700px;
            height: 40px;
            padding: 5px;
            font-size: 16px;
        }

        .container input[type="submit"] {
            width: 150px;
            height: 40px;
            font-size: 16px;
            background-color: darkslategrey;
            color: white;
            border: none;
            cursor: pointer;
        }
</style>
<h2>Index</h2>
@using (Html.BeginForm())
{
    <div class="container">
        <input type="text" name="maND" placeholder="nhập ID người dùng "/>
        <input type="submit" value="Tìm kiếm" />
    </div>
}
<div id="gridContent" style="text-align:center">
    @ViewBag.TB
    @grid.GetHtml(
        tableStyle: "table table-bordered table-hover grid-table",
        footerStyle: "grid-footer",
        fillEmptyRows: true,
        mode: WebGridPagerModes.Numeric,
        alternatingRowStyle: "alternatingRowStyle",
          columns: new[]  // colums in grid
         {
    grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
    grid.Column("id","Id Người dùng"), //the model fields to display
    grid.Column("tentaikhoan","Tên tài khoản"  ),
    grid.Column("matKhau","Mật khẩu"),
grid.Column("email","Email"),
grid.Column("FuName","FuName"),
grid.Column("Avartar","Ảnh User"),
grid.Column("sodu","Số dư"),
grid.Column("IDROLE1.ten","Tên Chức vụ"),
grid.Column("Chức năng", format: @<text>
    <a href="@Url.Action("Edit",
                        new { id = item.id})" class="edit-btn"><abbr title="Cập nhật dữ liệu"><img src="/images/edit.png" width="20" height="20" /></abbr></a>
    <a href="@Url.Action("Details",
                        new { idtk = item.id})" class="edit-btn"><abbr title="Xem chi tiết"><img src="/images/details.png" width="20" height="20" /></abbr></a>
    <a href="@Url.Action("Delete",
                        new { id = item.id})" class="edit-btn">
        <abbr title="Xóa dữ liệu">
            <img src="/images/delete.png" width="20" height="20" />
        </abbr>
    </a>
</text>),
}
)
</div>

tudong/tudong/Views/USERs/Login.cshtml
@model tudong.Models.LoginVM
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<link rel="stylesheet" href="@Url.Content("~/Content/Login.css")" />
<style>
    .{
       
    }
</style>
@using (Html.BeginForm("Login", "USERs", FormMethod.Post))
{   
    
    <div class="login-container">
        <div class="form-container">
            <h2>Login</h2>
            <div>
                <label for="Username">Tên đăng nhập:</label>
                @Html.TextBoxFor(m => m.Username, new { id = "Username" })
                @Html.ValidationMessageFor(m => m.Username)
            </div>
            <div>
                <label for="Password">Mật khẩu:</label>
                @Html.PasswordFor(m => m.Password, new { id = "Password" })
                @Html.ValidationMessageFor(m => m.Password)
            </div>
            <div>
                <input type="submit" value="Đăng nhập" />
            </div>
        </div>
    </div>
}

@if (!ViewData.ModelState.IsValid)
{
    <div class="error-summary">
        <p class="error-message">Đã xảy ra lỗi:</p>
        <ul>
            @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
            {
                <li>@error.ErrorMessage</li>
            }
        </ul>
    </div>
}